apiVersion: v1
kind: Namespace
metadata:
  name: ai-workloads
  labels:
    name: ai-workloads
    istio-injection: "false"    # set true later if you use a service mesh
    app.kubernetes.io/part-of: gpu-samples
    app.kubernetes.io/managed-by: argocd
