apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-secrets-manager-provider
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-secrets-manager
    targetRevision: 1.9.2
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
