apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-device-plugin
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://nvidia.github.io/k8s-device-plugin
    chart: nvidia-device-plugin
    # You can verify versions with:
    #   helm repo add nvdp https://nvidia.github.io/k8s-device-plugin
    #   helm search repo nvdp/nvidia-device-plugin --versions | head
    targetRevision: 0.18.0
    helm:
      values: |
        # Run the plugin as a DaemonSet on GPU nodes
        # You can adjust this later when you actually have GPU nodegroups
        nodeSelector:
          nvidia.com/gpu.present: "true"

        tolerations:
          - key: "nvidia.com/gpu"
            operator: "Exists"
            effect: "NoSchedule"
  destination:
    server: https://kubernetes.default.svc
    namespace: nvidia-device-plugin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
