apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-ebs-csi-driver
  namespace: argocd
spec:
  project: platform

  source:
    repoURL: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
    chart: aws-ebs-csi-driver
    targetRevision: 2.36.0
    helm:
      releaseName: aws-ebs-csi-driver
      values: |
        controller:
          serviceAccount:
            name: aws-ebs-csi-driver
            create: true
            annotations:
              eks.amazonaws.com/role-arn: arn:aws:iam::037776138351:role/versa-platform-dev-eks-ebs-csi-role

        node:
          serviceAccount:
            name: aws-ebs-csi-driver
            create: true
            annotations:
              eks.amazonaws.com/role-arn: arn:aws:iam::037776138351:role/versa-platform-dev-eks-ebs-csi-role

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true