apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter

  source:
    repoURL: https://charts.karpenter.sh
    chart: karpenter
    targetRevision: 1.11.0
    helm:
      releaseName: karpenter
      values: |
        serviceAccount:
          create: true
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::037776138351:role/versa-platform-dev-eks-karpenter-controller-role

        settings:
          clusterName: versa-platform-dev-eks
          clusterEndpoint: "https://9FDA62B21C7AC250D6136194E222AE51.gr7.us-east-1.eks.amazonaws.com"
          defaultInstanceProfile: "versa-platform-dev-eks-karpenter-node-instance-profile"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true