apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics
  namespace: argocd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-state-metrics
    targetRevision: 5.23.0
    helm:
      values: |
        replicas: 2
        podSecurityPolicy:
          enabled: false
        prometheusScrape: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true