apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.49.0
    helm:
      values: |
        loki:
          auth_enabled: false

          serviceAccount:
            annotations:
              eks.amazonaws.com/role-arn: arn:aws:iam::037776138351:role/versa-platform-dev-eks-loki-role

          storage:
            type: s3
            bucketNames:
              chunks: versa-platform-loki-logs
              ruler: versa-platform-loki-logs
              admin: versa-platform-loki-logs
            s3:
              region: us-east-1

          schemaConfig:
            configs:
              - from: 2020-10-24
                store: boltdb-shipper
                object_store: s3
                schema: v11
                index:
                  prefix: index_
                  period: 24h

          compactor:
            enabled: true
            retention_enabled: true
            retention_delete_delay: 2h
            retention_delete_worker_count: 2
  destination:
    namespace: loki
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true