apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-workloads
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/smburabari/platform-gitops.git
    targetRevision: main
    path: apps/workloads
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
